version: '1.0'

stages:
- build
- push

steps:

  # |--------------------------------------------------------------|
  # | Stage 1: Build Docker images with different versions of Helm |
  # |--------------------------------------------------------------|


  # Helm v2.11.0
  build_2_11_0:
    type: build
    stage: build
    image_name: codefresh/cfstep-helm
    build_arguments:
      - HELM_VERSION=2.11.0
    tag: 2.11.0-${{CF_SHORT_REVISION}}

  # |---------------------------------------------|
  # | Stage 2: Push all Docker Images built above |
  # |---------------------------------------------|

  # Helm v2.11.0
  push_2_11_0:
    type: push
    stage: push
    candidate: ${{build_2_11_0}}
    registry: dockerhub
    tag: 2.11.0
    when:
      branch:
        only:
          - master

  # Latest tag (2.11.0)
  push_latest:
    type: push
    stage: push
    candidate: ${{build_2_11_0}}
    registry: dockerhub
    tag: latest
    when:
      branch:
        only:
          - master
